import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../Components/Navbar';
// import About from '../Components/About';
import { QueryContextWrapper } from '../context/queryContext';
import { CartContextWrapper } from '../context/cartContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'E-com',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryContextWrapper>
          <CartContextWrapper>
            <Navbar /> 
            <div className="mt-14">{children}</div>
          </CartContextWrapper>
        </QueryContextWrapper>
        {/* <About /> */}
      </body>
    </html>
  );
}
